[project]
name = "assignment-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.0.0",
    "pygame>=2.6.1",
    "streamlit>=1.43.0",
    "streamlit-lottie>=0.0.5",
]
